### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [oleksiikutuzov/IKEA-VINDSTYRKA#3]
Hello!

I found this project from https://hackaday.com/2023/03/16/taking-apart-ikeas-latest-air-quality-sensor/

Could you please add information about the license of this repository — is it allowed to copy, change and use the text and images (and maybe a code in future) in any purpose?
It would be great to see any popular open source license.

**Comment by oleksiikutuzov** [comment]
Indeed, thanks for the notice. Added.

**Comment by vazhnov** [comment]
MIT license — great!
Thank you!
